---
- hosts: localhost
  tasks:
    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - google-chrome
        - google-cloud-sdk
        - visual-studio-code
        - iterm2
        - docker
        - intellij-idea
        - github
    
    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'autoconf',
          'curl',
          'gradle',
          'java',
          'kotlin'
        ]
        state: present
        update_homebrew: yes

    - name: Create symbolic link 
      become: yes
      file:
        src: "/usr/local/opt/openjdk/libexec/openjdk.jdk"
        dest: "/Library/Java/JavaVirtualMachines/openjdk.jdk"
        state: link
